---
# Phase 1 configuration
ipsec_p1_state: present
ipsec_p1_description: "VPN-to-existing-site"
vpn_interface: "VPN_Interface"
remote_gateway: "10.1.1.10"
local_gateway: "10.1.1.20"
p1_iketype: "ikev2"
p1_authentication_method: "pre_shared_key"
p1_preshared_key: "iwas"
p1_myid_type: "myaddress"
p1_peerid_type: "peeraddress"
p1_lifetime: 28800
p1_nat_traversal: "on"
p1_dpd_delay: 10
p1_dpd_maxfail: 5




# Phase 2 Configuration
ipsec_p2_description: "VPN-to-existing-site-P2" 
ipsec_p2_state: present
ipsec_p2_mode: "vti"
ipsec_p2_protocol: "esp"
ipsec_p2_local: "10.6.106.2/30"
ipsec_p2_remote: "10.6.106.1"
ipsec_p2_aes: true
ipsec_p2_aes_len: auto
ipsec_p2_sha256: true
ipsec_p2_pfsgroup: 14
ipsec_p2_lifetime: 3600

# VPN interface 
vpn_interfaces:
  - descr: "Tunnel_Interface"
    interface: "ipsec1"
    enable: true

# VPN Tunnel Gateway
ipsec_tunnel_gateway_name: "TUNNEL_INTERFACE_VTIV4"
ipsec_tunnel_gateway_descr: "IPsec VTI tunnel gateway"
ipsec_tunnel_gateway_interface: "TUNNEL_INTERFACE"
ipsec_tunnel_gateway_gateway: "dynamic"
ipsec_tunnel_gateway_ipprotocol: inet
ipsec_tunnel_gateway_state: "present"

# VPN Route
vpn_route_descr: "vpn_route"
vpn_route_destination_network: "192.168.2.0/24"
vpn_route_state: "present"
