---
- name: "PfSense DHCP einrichten"
  hosts: localhost
  tasks:

  - name: setup hostname and domain
    pfsense_setup:
      hostname: acme
      domain: corp.com

  - name: setup theme
    pfsense_setup:
      webguicss: pfSense-dark

  - name: timezone and language
    pfsense_setup:
      timezone: Europe/Paris
      language: fr
      timeservers: 

  - name: Add interface
    pfsense_interface:
      descr: 
      interface: 
      ipv4_address:
      ipv4_gateway:
      ipv4_prefixlen: 24
      ipv4_type: static
      ipv6_address:
      ipv6_gateway:
      ipv6_prefixlen: 128
      ipv6_type: static
      enable: True

  - name: Add  VLAN
    pfsense_vlan:
      interface: mvneta0
      vlan_id: 100
      descr: voice
      priority: 5
      state: present

  - name: Configure DHCP server on IOT interface
    pfsense_dhcp_server:
      interface: IOT
      enable: true
      range_from: 192.168.1.100
      range_to: 192.168.1.200
      netmask: 255.255.255.0
      gateway: 192.168.1.1
      domain: example.com
      defaultleasetime: 86400
      maxleasetime: 172800

- name: Enable DNS Resolver with some options
  pfsense_dns_resolver:
    state: present
#    enablessl: true
#    sslcert: "webConfigurator default"
    dnssec: true
    regdhcp: true
#    regdhcpstatic: true
  hosts:
        - { host: test, domain: home.local, ip: 192.168.1.100, descr: "Example host override",
            aliases: [{ host: test-admin, domain: home.local, description: "Example aliases" }] }
  
- name: Add operator user
  pfsense_user:
    name: operator
    descr: Operator
    scope: user
    groups: [ 'Operators' ]
    priv: [ 'page-all', 'user-shell-access' ]