---
- name: "Setup VLANs on pfSense"
  hosts: switches
  gather_facts: false
  collections:
    - pfsensible.core

  tasks:

  - name: Override device configuration of all VLANs with provided configuration
    cisco.ios.ios_vlans:
      config:
        - name:  {{ item.description }}
          state: active
          vlan_id: {{ item.vlan_id }}
          shutdown: disabled
      state: overridden
    loop: "{{ vlans }}"



  - name: Configure trunk ports
    ios_config:
      lines:
        - interface GigabitEthernet1/0/1
        - switchport mode trunk
        - "switchport trunk allowed vlan {{allowed_trunk_ports}}"
      save_when: modified