---
- name: "IPSec VPN zum bestehenden Standort"
  hosts: pfsense
  gather_facts: false
  tasks:
    - name: "Configure IPSec Phase 1 (IKE)"
      pfsensible.core.pfsense_ipsec:
        state: present
        descr: "VPN-to-existing-site"
        interface: "VPN_Interface"
        remote_gateway: "10.1.1.10"
        iketype: "ikev2"
        authentication_method: "pre_shared_key"
        preshared_key: "iwas"
        myid_type: "address"
        myid_data: "10.1.1.20"
        peerid_type: "address"
        peerid_data: "10.1.1.10"
        lifetime: 28800
        nat_traversal: "on"
        dpd_delay: 10
        dpd_maxfail: 5

    - name: "Configure IPSec Phase 2 (ESP)"
      pfsensible.core.pfsense_ipsec_p2:
        p1_descr: "VPN-to-existing-site"
        descr: "VPN-to-existing-site-P2"
        state: present
        mode: "vti"
        protocol: "esp"
        local: "10.6.106.2/30"
        remote: "10.6.106.1"
        aes: true
        aes_len: auto
        sha256: true
        pfsgroup: 14
        lifetime: 3600

    - name: Add VPN interface
      pfsensible.core.pfsense_interface:
        descr: "{{ item.descr }}"
        interface: "{{ item.interface }}"
        enable: "{{ item.enable | default(True) }}"
      loop: "{{ vpn_interfaces }}"

    - name: Add tunnel VTI gateway
      pfsensible.core.pfsense_gateway:
        name: "TUNNEL_INTERFACE_VTIV4"
        descr: "IPsec VTI tunnel gateway"
        interface: "TUNNEL_INTERFACE"
        gateway: dynamic
        ipprotocol: inet
        state: present

    - name: Add VPN route
      pfsensible.core.pfsense_route:
        descr: vpn_route
        gateway: "TUNNEL_INTERFACE_VTIV4"
        network: "192.168.2.0/24"
        state: present

    - name: "Allow traffic through tunnel from existing site"
      pfsensible.core.pfsense_rule:
        name: "Allow existing site to new site"
        action: pass
        interface: IPsec
        ipprotocol: inet
        source: "192.168.2.0/24"
        destination: "192.168.1.0/24"
        state: present

    - name: "Allow LAN to existing site through VPN"
      pfsensible.core.pfsense_rule:
        name: "Allow new site to existing site"
        action: pass
        interface: LAN_Interface
        ipprotocol: inet
        source: "192.168.1.0/24"
        destination: "192.168.2.0/24"
        state: present
