---
- name: Configure OpenVPN Site-to-Site Client
  hosts: pfsense
  gather_facts: no
  tasks:
  - name: Add VPN Tunnel
    pfsense_ipsec:
      state: present
      descr: site-to-site-tunnel
      interface: VPN_Interface
      remote_gateway: 10.10.10.2
      iketype: ikev2
      authentication_method: pre_shared_key
      preshared_key: "{{ ipsec_shares_secret }}"

  - name: Add simple phase2
    pfsense_ipsec_p2:
      p1_descr: site-to-site-tunnel
      descr: site-to-site-tunnel_p2
      state: present
      mode: vti
      local: 10.10.10.10
      remote: 10.10.10.2
      aes: True
      aes_len: auto
      sha256: True
