---
- name: "IPSec VPN zum bestehenden Standort"
  hosts: pfsense
  gather_facts: false
  collections:
    - pfsensible.core
  
  tasks:
    - name: "Configure IPSec Phase 1 (IKE)"
      pfsense_ipsec:
        state: present
        descr: "VPN-to-existing-site"
        interface: "VPN_Interface"
        remote_gateway: "10.1.1.20"
        iketype: "ikev2"
        authentication_method: "pre_shared_key"
        preshared_key: "iwas"
        myid_type: "address"
        myid_data: "10.1.1.10"
        peerid_type: "address"
        peerid_data: "10.1.1.20"
        lifetime: 28800
        nat_traversal: "on"
        dpd_delay: 10
        dpd_maxfail: 5

    - name: "Configure IPSec Phase 2 (ESP)"
      pfsense_ipsec_p2:
        p1_descr: "VPN-to-existing-site"
        descr: "VPN-to-existing-site-P2"
        state: present
        mode: "vti"
        protocol: "esp"
        local: "10.6.106.2/30"
        remote: "10.6.106.1"
        aes: true
        aes_len: auto
        sha256: true
        pfsgroup: 14
        lifetime: 3600

    - name: Add VPN interface
      pfsense_interface:
          descr: "{{ item.descr }}"
          interface: "{{ item.interface }}"
          ipv4_address: "{{ item.ipv4_address | default(omit) }}"
          ipv4_gateway: "{{ item.ipv4_gateway | default(omit) }}"
          ipv4_prefixlen: "{{ item.ipv4_prefixlen | default(24) }}"
          ipv4_type: "{{ item.ipv4_type | default('static') }}"
          ipv6_address: "{{ item.ipv6_address | default(omit) }}"
          ipv6_gateway: "{{ item.ipv6_gateway | default(omit) }}"
          ipv6_prefixlen: "{{ item.ipv6_prefixlen | default(128) }}"
          ipv6_type: "{{ item.ipv6_type | default('static') }}"
          enable: "{{ item.enable | default(True) }}"
      loop: "{{ vpn_interfaces }}"

    - name: Add tunnel VTI gateway
      pfsensible.core.pfsense_gateway:
        name: "TUNNEL_INTERFACE_VTIV4"        
        descr: "IPsec VTI tunnel gateway"
        interface: "TUNNEL_INTERFACE"         
        gateway: dynamic              
        ipprotocol: inet
        state: present
     
    - name: Add VPN route
      pfsense_route:
        descr: vpn_route
        gateway: IPSECVTI_VTIV4
        network: "192.168.2.0/24"
        state: present

    - name: "Allow all through VPN"
      pfsense_rule:
        name: "Allow all through VPN"
        action: pass
        interface: "VPN_Interface"
        ipprotocol: inet
        protocol: any
        source: any
        destination: any
        state: present

    - name: "Allow NAT-T (UDP 4500)"
      pfsense_rule:
        name: "Allow NAT-T from existing site"
        action: pass
        interface: "VPN_Interface"
        ipprotocol: inet
        protocol: udp
        source: "10.1.1.10"
        destination: "10.1.1.20"
        destination_port: "4500"
        state: present

    - name: "Allow IPSec ESP"
      pfsense_rule:
        name: "Allow ESP from existing site"
        action: pass
        interface: "VPN_Interface"
        ipprotocol: inet
        protocol: esp
        source: "10.1.1.10"
        destination: "10.1.1.20"
        state: present

    - name: "Allow traffic through tunnel from existing site"
      pfsense_rule:
        name: "Allow existing site to new site"
        action: pass
        interface: IPsec
        ipprotocol: inet
        source: "192.168.2.0/24"
        destination: "192.168.1.0/24"
        state: present

    - name: "Allow LAN to existing site through VPN"
      pfsense_rule:
        name: "Allow new site to existing site"
        action: pass
        interface: lan
        ipprotocol: inet
        source: "192.168.1.0/24"
        destination: "192.168.2.0/24"
        state: present